language: ruby
before_install:
   - rvm install 2.3.1
rvm:
  - 2.3.1
services:
  - postgresql
before_script:
  - psql -c 'create database mono_test;' -U postgres
  - bundle exec padrino rake db:reset -e test
