default: &default
    adapter: postgresql
    encoding: UTF-8

test:
    <<: *default
    database: mono_test
    host: localhost
    port: 5432
    username: postgres
    password: wRto7oD8J

development:
    adapter: postgresql
    database: mono_development
    host: localhost
    port: 5432
    username: postgres
    password: wRto7oD8J